### PR TITLE
Definition of Path to Script needed during install

### PR DESCRIPTION
**Pull request by mikestratton**
The Path to Script is undefined during the install resulting in the error message: "Error: Could not connect to database (Access denied for user 'root'@'localhost' (using password: YES)). Check your database settings are correct." Using: http://yoursite.com/Indication/get.php or any variation of this does not work. Once the script has been defined, a feature could be added that allows the user to just enter their domain name to point to the script.

### CODE REVIEW

**Comment by joshf** [comment]
The error is from mysql so path to script has nothing to do with it :)

You can change the path to script in settings, but setting just the domain would be a good idea!

**Comment by mikestratton** [comment]
Thanks for your reply. I can connect to the database locally using Wordpress, Drupal, and my own applications. My database is configured correctly, including password and user name, and I list the database name in the install, so the error is not a database connection. I will look into it further to see if I can validate what is happening that is causing the error.

**Comment by mikestratton** [comment]
Hello Josh,
 
I am working on a hacker-fest sponsored by GitHub and Digital Ocean: https://hacktoberfest.digitalocean.com/
I am trying to find a project that I can contribute to and have pull requests merged. Do you have any projects that I can help with?
 
I work with:
Java, PHP, C++
SQL/MySql
CSS/ Front End
Graphic Design.
 
 
  
 
Michael A. Stratton
Freelance Web Developer
 
Web: http://www.mikestratton.net
Email: mike@mikestratton.net
Cell: (330)802-0285

 
 
--------- Original Message --------- Subject: Re: [Indication] Definition of Path to Script needed during install (#12)

**Comment by mikestratton** [comment]
The problem was the database connection. I fixed this and I can now connect. I am still running into some problems with the install.

**Comment by joshf** [comment]
What errors exactly?

**Comment by mikestratton** [comment]
It's probably on my end, not sure what the source is. I will replicate what I am doing.

*****************************************************
*****************************************************
Using the following code, I validate that I can connect to the database:
<?php 
$servername = "127.0.0.1";  
$username = "root";
$password = "password";
// Create connection
$conn = mysql_connect($servername, $username, $password) or die("Unable to Connect");
echo "Connected successfully";
/* 
***NOTE*** 
Unable to connect using servername = localhost 
Replace the line:
$servername = "127.0.0.1";  
with the line:
$servername = "localhost";  
Causes the following error:
Warning: mysql_connect(): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. in C:\xampp\htdocs\tools\db_connect.php on line 7
Unable to Connect
*/
?> 
*****************************************************
*****************************************************
I then complete the form as follows:
Database Host: 127.0.0.1
Database User: root
Database Password: password
Database Name: indication     //indication database created via phpMyAdmin
Website Name: Indication
Path to Script: http://localhost/Indication
User: admin
Email: mike {at} mikestratton {dot} net
Password: password2
*****************************************************
*****************************************************
After clicking install, I get the following error:
Error: Could not connect to database (Access denied for user 'root'@'localhost' (using password: YES)). Check your database settings are correct.
*****************************************************
*****************************************************
I hit the back button in the browser and I get the following message:

"Information: Indication has already been installed! You can login here or to reinstall the app please delete your config.php file and run this installer again."
*****************************************************
*****************************************************
I click to login and it does not recognize my user name and password. I log into phpMyAdmin and the indication database is empty.
*****************************************************
*****************************************************
If I delete the config.php file and try again, the same error happens.
*****************************************************
*****************************************************
I have tried resetting the password for root user via phpmyadmin with the same problem.
*****************************************************
*****************************************************
The problem may be the result of my misconfiguration of users within phpMyAdmin?
*****************************************************
*****************************************************
I hope I am not sending you on a wild goose chase as a result of me being lost in the wild.

**Comment by joshf** [comment]
I dont understand why it wont connect but it shouldn't write the config file if mysql cant connect

**Comment by joshf** [comment]
I also noticed in your example you use mysql, I use mysqli as mysql is depreciated

**Comment by mikestratton** [comment]
I can change the line to mysqli but I am not sure how this is relevant. This code only validates that a database connection can be made.

**Comment by joshf** [comment]
No not relevant, just for future for you!

The "Access denied for user 'root'@'localhost' (using password: YES)" is from mysql complaining that either your username or password is wrong or not allowed for the host. I cant find a problem with the code so i think its a configuration error on your system. Try looking here http://superuser.com/questions/603026/mysql-how-to-fix-access-denied-for-user-rootlocalhost

**Comment by joshf** [comment]
Remove the @ from the following line and you will get the full error    

@$con = mysqli_connect($dbhost, $dbuser, $dbuser, $dbname);

**Comment by joshf** [comment]
This was a bug after all, fixed now @mikestratton

**Pull request closed without merging**
